apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-provisioner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hostpath-provisioner
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: hostpath-provisioner
  namespace: kube-system
---
kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
  namespace: kube-system
spec:
  serviceAccountName: hostpath-provisioner
  containers:
    - name: hostpath-provisioner
      image: guillaumerose/hostpath-provisioner:latest
      imagePullPolicy: "IfNotPresent"
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: pv-volume
          mountPath: /var/lib/hostpath-provisioner
  volumes:
    - name: pv-volume
      hostPath:
        path: /var/lib/hostpath-provisioner
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: example-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: example.com/hostpath
